language: php
sudo: false

php:
  - 7.0
  - 7.1

cache:
  directories: [$HOME/.composer/cache/files]

#disable xdebug
before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - composer install --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader --classmap-authoritative

script: vendor/bin/phpunit

notifications:
  email:
    - andrieu.travail@gmail.com
